route:
  receiver: pagerduty

receivers:
  - name: pagerduty
    pagerduty_configs:
      - service_key_file: "/run/secrets/pagerduty_integration_key"
        url: "https://events.eu.pagerduty.com/generic/2010-04-15/create_event.json"
        send_resolved: true
