global:
  scrape_interval: 15s

rule_files:
  - "rules/*.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alert-manager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "localhost:9090"

  - job_name: "alert-manager"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "alert-manager:9093"

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "node-exporter:9100"
