groups:
  - name: example-alerts

    rules:
      - alert: Node is down
        expr: up{job="node"} == 0
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Node is DOWN!"
          description: "This is a test description!"
